### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by ayushmaan-IIITD** [alizat/Chemogenomic-DTI-Prediction-Methods#1]
I am getting an error on line number 73 of start.m file 
"crossValidation(Y')" and subsequent errors because of Y'

Can I get a little help to resolve it?

**Comment by ayushmaan-IIITD** [comment]
The error is as follows:

Error using  * 
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number
of rows in the second matrix. To perform elementwise multiplication, use '.*'.

Error in alg_template>alg_np (line 61)
    yt = (St * Y')';

Error in alg_template (line 19)
    Yhat = predFn(Y,Sd,St,test_ind,left_out);

Error in nfold (line 77)
        y3 = alg_template(y2,predictionMethod,test_ind,left_out); % predict! (y3 is the predicted matrix)

Error in crossValidation (line 72)
        [AUCs(i), AUPRs(i)] = nfold(Y,seed,i);

Error in start (line 73)
            crossValidation(Y');

**Comment by alizat** [comment]
Dear ayushmaan,
I tried running the code currently on the GitHub repo (particularly, the code under "1. Main") without any modification. The code ran successfully with no issues. I was running the code on MATLAB R2015a. 

As such, I will need you to give me more information:
- Did you run the code from the GitHub repo without any modifications? If not, what are your modifications?
- What dataset were you using (NR, GPCR, IC, E)?
- What are the dimensions of the matrices being multiplied together? Use 'size(St)' and 'size(Y')' to know the answer (e.g. add these statements to the code right before the error line). Based on the answer, you will need to backtrack to see what caused the problem.

Answering the above questions may solve the issue. If not, I can keep investigating the issue with you. Furthermore, since there are global variables that are declared in the code, make sure to regularly 'clear all' as these global variables may occasionally mess up things.

Yours Sincerely,
Ali

**Comment by ayushmaan-IIITD** [comment]
Dear Ali,
             Yes, I ran the code currently on the GitHub repo by running the script "start.m" in "1. Main") without any modifications. I ran the code on MATLAB R2018b.

I was getting an error on IC dataset but then the next day, I started getting an error on NR dataset because according to me, I re-downloaded(not really downloaded; you will find out later in this message) the dataset files.
The dimensions of the matrix in case of IC dataset error were as follows:
St : 26x26
Y' : 204x210

The download link for the dataset which you have mentioned int the "data" folder doesn't really download the dataset files, it simply opens txt files on my browser window. Then, I had to copy and paste them in an empty text file one by one. I think the errors may have creeped up because of that.

It would be very helpful of you if you could mail me those dataset files which you ran on your system and got correct results

Yours Sincerely,
Ayushmaan

**Comment by alizat** [comment]
Dear Ayushmaan,
When you download a text file from the internet, you may right-click the link and select "Save Link As..." (instead of opening the link). Another alternative would be to open the link and then "Ctrl+S" to save the text file (instead of copy-pasting the content of the page).

**_In any case, I just uploaded the data files to the "1. Main/data/" folder on the GitHub repo, so you don't need to manually download the data anymore. Let me know if running the code works for you now._**

By the way, the statistics for the different datasets are as follows:
NR: 54 drugs, 26 targets
GPCR: 223 drugs, 95 targets
IC: 210 drugs, 204 targets
E: 445 drugs, 664 targets

You may notice that the dimensions displayed (St : 26x26, Y' : 204x210) belong to two different datasets, which would naturally lead to an error.

Yours Sincerely,
Ali

**Comment by ayushmaan-IIITD** [comment]
Dear Ali,
The code is running fine now. Thank you so much for your help.

Yours Sincerely,
Ayushmaan
